# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Chia' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Chia
    pod 'Firebase/Firestore','~> 5.15.0'
    pod 'Firebase/Auth','~> 5.15.0'
    pod 'Firebase/Storage','~> 5.15.0'
    pod 'Firebase/Core'
    pod 'GoogleAppMeasurement', '~> 5.4.0'
    pod 'SDWebImage', '~>4.4.2’
    pod 'JGProgressHUD', '~>2.0.3'
end
